// <auto-generated />
using System;
using CalculadoraCusto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalculadoraCusto.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726150622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraCusto.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("UnidadePadrao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade_padrao");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("ingredientes", (string)null);
                });

            modelBuilder.Entity("CalculadoraCusto.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("MargemLucroPadrao")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margem_lucro_padrao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("QuantidadeProduzida")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_produzida");

                    b.Property<string>("UnidadeProduzida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidade_produzida");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Nome");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("CalculadoraCusto.Domain.Entities.ReceitaIngrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<string>("NomeIngrediente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_ingrediente");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("QuantidadeComprada")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_comprada");

                    b.Property<decimal>("QuantidadeUtilizada")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_utilizada");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receita_id");

                    b.Property<string>("UnidadeCompra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade_compra");

                    b.Property<string>("UnidadeUtilizada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidade_utilizada");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("receita_ingredientes", (string)null);
                });

            modelBuilder.Entity("CalculadoraCusto.Domain.Entities.ReceitaIngrediente", b =>
                {
                    b.HasOne("CalculadoraCusto.Domain.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CalculadoraCusto.Domain.Entities.Receita", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalculadoraCusto.Domain.Entities.Receita", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
